# Generated by Django 5.1.4 on 2024-12-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="description",
            new_name="icon",
        ),
    ]
